# TensorFlow Dataset API

**Learning Objectives**
1. Learn how use tf.data to read data from memory
1. Learn how to use tf.data in a training loop
1. Learn how use tf.data to read data from disk
1. Learn how to write production input pipelines with feature engineering (batching, shuffling, etc.)


In this notebook, we will start by refactoring the linear regression we implemented in the previous lab so that is takes its data from a`tf.data.Dataset`, and we will learn how to implement **stochastic gradient descent** with it. In this case, the original dataset will be synthetic and read by the `tf.data` API directly  from memory.

In a second part, we will learn how to load a dataset with the `tf.data` API when the dataset resides on disk.

In [74]:
import os
import warnings

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
warnings.filterwarnings("ignore")

import json
import math
from pprint import pprint

import numpy as np
import tensorflow as tf

print(tf.version.VERSION)

2.12.0


## Loading data from memory

### Creating the dataset

Let's consider the synthetic dataset of the previous section:

In [75]:
N_POINTS = 10
X = tf.constant(range(N_POINTS), dtype=tf.float32)
Y = 2 * X + 10

We begin with implementing a function that takes as input


- our $X$ and $Y$ vectors of synthetic data generated by the linear function $y= 2x + 10$
- the number of passes over the dataset we want to train on (`epochs`)
- the size of the batches the dataset (`batch_size`)

and returns a `tf.data.Dataset`: 

**Remark:** Note that the last batch may not contain the exact number of elements you specified because the dataset was exhausted.

If you want batches with the exact same number of elements per batch, we will have to discard the last batch by
setting:

```python
dataset = dataset.batch(batch_size, drop_remainder=True)
```

We will do that here.

**Lab Task #1:** Complete the code below to 
1. instantiate a `tf.data` dataset using [tf.data.Dataset.from_tensor_slices](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensor_slices).
2. Set up the dataset to 
  * repeat `epochs` times,
  * create a batch of size `batch_size`, ignoring extra elements when the batch does not divide the number of input elements evenly.

In [93]:
def create_dataset(X, Y, epochs, batch_size):
    dataset = tf.data.Dataset.from_tensor_slices((X,Y))  # TODO: Your code here.
    dataset = dataset.repeat(epochs).batch(batch_size, drop_remainder=True)
    return dataset

Let's test our function by iterating twice over our dataset in batches of 3 datapoints:

In [94]:
BATCH_SIZE = 3
EPOCH = 2

dataset = create_dataset(X, Y, epochs=EPOCH, batch_size=BATCH_SIZE)

for i, (x, y) in enumerate(dataset):
    print(i)
    print("x:", x.numpy(), "y:", y.numpy())
    assert len(x) == BATCH_SIZE
    assert len(y) == BATCH_SIZE
assert EPOCH

0
x: [0. 1. 2.] y: [10. 12. 14.]
1
x: [3. 4. 5.] y: [16. 18. 20.]
2
x: [6. 7. 8.] y: [22. 24. 26.]
3
x: [9. 0. 1.] y: [28. 10. 12.]
4
x: [2. 3. 4.] y: [14. 16. 18.]
5
x: [5. 6. 7.] y: [20. 22. 24.]


### Loss function and gradients

The loss function and the function that computes the gradients are the same as before:

In [95]:
def loss_mse(X, Y, w0, w1):
    Y_hat = w0 * X + w1
    errors = (Y_hat - Y) ** 2
    return tf.reduce_mean(errors)


def compute_gradients(X, Y, w0, w1):
    with tf.GradientTape() as tape:
        loss = loss_mse(X, Y, w0, w1)
    return tape.gradient(loss, [w0, w1])

### Training loop

The main difference now is that now, in the traning loop, we will iterate directly on the `tf.data.Dataset` generated by our `create_dataset` function. 

We will configure the dataset so that it iterates 250 times over our synthetic dataset in batches of 2.

**Lab Task #2:** Complete the code in the cell below to call your dataset above when training the model. Note that the `step, (X_batch, Y_batch)` iterates over the `dataset`. The inside of the `for` loop should be exactly as in the previous lab. 

In [96]:
EPOCHS = 2500
BATCH_SIZE = 2
LEARNING_RATE = 0.02

MSG = "STEP {step} - loss: {loss}, w0: {w0}, w1: {w1}"

w0 = tf.Variable(0.0)
w1 = tf.Variable(0.0)

dataset = create_dataset(X, Y, EPOCHS, BATCH_SIZE)
for x in dataset:
    print(x)
    break

for step, (X_batch, Y_batch) in enumerate(dataset):

    dw0, dw1 = compute_gradients(X, Y, w0, w1)
    w0.assign_sub(dw0 * LEARNING_RATE)
    w1.assign_sub(dw1 * LEARNING_RATE)

    if step % 100 == 0:
        loss = loss_mse(X, Y, w0, w1)
        print(MSG.format(step=step, loss=loss, w0=w0.numpy(), w1=w1.numpy()))

assert loss < 0.0001
assert abs(w0 - 2) < 0.001
assert abs(w1 - 10) < 0.001

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 12.], dtype=float32)>)
STEP 0 - loss: 35.70719528198242, w0: 4.079999923706055, w1: 0.7599999904632568
STEP 100 - loss: 2.6017532348632812, w0: 2.4780430793762207, w1: 7.002389907836914
STEP 200 - loss: 0.26831889152526855, w0: 2.153517961502075, w1: 9.037351608276367
STEP 300 - loss: 0.027671903371810913, w0: 2.0493006706237793, w1: 9.690855979919434
STEP 400 - loss: 0.0028539239428937435, w0: 2.0158326625823975, w1: 9.90071964263916
STEP 500 - loss: 0.0002943490108009428, w0: 2.005084753036499, w1: 9.96811580657959
STEP 600 - loss: 3.0356444767676294e-05, w0: 2.0016329288482666, w1: 9.989760398864746
STEP 700 - loss: 3.1322738323069643e-06, w0: 2.0005245208740234, w1: 9.996710777282715
STEP 800 - loss: 3.2238213520940917e-07, w0: 2.0001683235168457, w1: 9.998944282531738
STEP 900 - loss: 3.369950718479231e-08, w0: 2.000054359436035, w1: 9.99965858459

## Loading data from disk

### Locating the CSV files

We will start with the **taxifare dataset** CSV files that we wrote out in a previous lab. 

The taxifare datast files been saved into `../data`.

Check that it is the case in the cell below, and, if not, regenerate the taxifare
dataset by running the provious lab notebook:

In [34]:
!ls -l ../data/taxi*.csv

-rw-r--r-- 1 jupyter jupyter 123590 May 12 07:39 ../data/taxi-test.csv
-rw-r--r-- 1 jupyter jupyter 579055 May 12 07:39 ../data/taxi-train.csv
-rw-r--r-- 1 jupyter jupyter 399562 May 12 07:39 ../data/taxi-valid.csv


### Use high-level tf.data API to read the CSV files

The `tf.data` API can easily read csv files using the helper function

[tf.data.experimental.make_csv_dataset](https://www.tensorflow.org/api_docs/python/tf/data/experimental/make_csv_dataset)

This function includes many convenient features, so the data is easy to work with. This includes:

- This function returns OrderedDict of multiple tensors.
- Using the column headers as dictionary keys.
- Automatically determining the type of each column.

If you have TFRecords (which is recommended), you may use

[tf.data.experimental.make_batched_features_dataset](https://www.tensorflow.org/api_docs/python/tf/data/experimental/make_batched_features_dataset)

The first step is to define 

- the feature names into a list `CSV_COLUMNS`
- their default values into a list `DEFAULTS`

In [122]:
CSV_COLUMNS = [
    "fare_amount",
    "pickup_datetime",
    "pickup_longitude",
    "pickup_latitude",
    "dropoff_longitude",
    "dropoff_latitude",
    "passenger_count",
    "key",
]
LABEL_COLUMN = "fare_amount"
DEFAULTS = [[0.0], ["na"], [0.0], [0.0], [0.0], [0.0], [0.0], ["na"]]
BATCH_SIZE=1

Let's now wrap the call to `make_csv_dataset` into its own function that will take only the file pattern (i.e. glob) where the dataset files are to be located:

**Lab Task #3:** Complete the code in the `create_dataset(...)` function below to return a `tf.data` dataset made from the `make_csv_dataset`. Have a look at the [documentation here](https://www.tensorflow.org/api_docs/python/tf/data/experimental/make_csv_dataset). The `pattern` will be given as an argument of the function but you should set the `batch_size`, `column_names` and `column_defaults`.

In [123]:
def create_dataset(
    pattern,
) -> tf.data.Dataset:
    dataset = tf.data.experimental.make_csv_dataset(
        pattern,
        batch_size=BATCH_SIZE,
        column_names=CSV_COLUMNS,
        column_defaults=DEFAULTS,
    )

    return dataset




tempds = create_dataset("../data/taxi-train*")
print(tempds)

<_PrefetchDataset element_spec=OrderedDict([('fare_amount', TensorSpec(shape=(1,), dtype=tf.float32, name=None)), ('pickup_datetime', TensorSpec(shape=(1,), dtype=tf.string, name=None)), ('pickup_longitude', TensorSpec(shape=(1,), dtype=tf.float32, name=None)), ('pickup_latitude', TensorSpec(shape=(1,), dtype=tf.float32, name=None)), ('dropoff_longitude', TensorSpec(shape=(1,), dtype=tf.float32, name=None)), ('dropoff_latitude', TensorSpec(shape=(1,), dtype=tf.float32, name=None)), ('passenger_count', TensorSpec(shape=(1,), dtype=tf.float32, name=None)), ('key', TensorSpec(shape=(1,), dtype=tf.string, name=None))])>


Note that this is a prefetched dataset, where each element is an `OrderedDict` whose keys are the feature names and whose values are tensors of shape `(1,)` (i.e. vectors).

Let's iterate over the two first element of this dataset using `dataset.take(2)` and let's convert them ordinary Python dictionary with numpy array as values for more readability:

In [124]:
for data in tempds.take(2):
    pprint({k: v.numpy() for k, v in data.items()})
    print(f"{'-'*20}\n")

{'dropoff_latitude': array([40.75573], dtype=float32),
 'dropoff_longitude': array([-73.97731], dtype=float32),
 'fare_amount': array([6.9], dtype=float32),
 'key': array([b'1792'], dtype=object),
 'passenger_count': array([1.], dtype=float32),
 'pickup_datetime': array([b'2011-10-05 08:14:00 UTC'], dtype=object),
 'pickup_latitude': array([40.749386], dtype=float32),
 'pickup_longitude': array([-73.99015], dtype=float32)}
--------------------

{'dropoff_latitude': array([40.75579], dtype=float32),
 'dropoff_longitude': array([-73.98281], dtype=float32),
 'fare_amount': array([6.], dtype=float32),
 'key': array([b'1375'], dtype=object),
 'passenger_count': array([2.], dtype=float32),
 'pickup_datetime': array([b'2013-03-19 16:47:38 UTC'], dtype=object),
 'pickup_latitude': array([40.75094], dtype=float32),
 'pickup_longitude': array([-73.99427], dtype=float32)}
--------------------



### Transforming the features

What we really need is a dictionary of features + a label. So, we have to do two things to the above dictionary:

1. Remove the unwanted column "key"
1. Keep the label separate from the features

Let's first implement a funciton that takes as input a row (represented as an `OrderedDict` in our `tf.data.Dataset` as above) and then returns a tuple with two elements:

* The first element beeing the same `OrderedDict` with the label dropped
* The second element beeing the label itself (`fare_amount`)

Note that we will need to also remove the `key` and `pickup_datetime` column, which we won't use.

**Lab Task #4a:** Complete the code in the `features_and_labels(...)` function below. Your function should return a dictionary of features and a label. Keep in mind `row_data` is already a dictionary and you will need to remove the `pickup_datetime` and `key` from `row_data` as well.

In [125]:
UNWANTED_COLS = ["pickup_datetime", "key"]


def features_and_labels(row_data):
    label = row_data.pop(LABEL_COLUMN)
    features = row_data

    for unwanted_col in UNWANTED_COLS:
        features.pop(unwanted_col)

    return features, label

Let's iterate over 2 examples from our `tempds` dataset and apply our `feature_and_labels`
function to each of the examples to make sure it's working:

In [126]:
LABEL_COLUMN


'fare_amount'

In [127]:
for row_data in tempds.take(2):
    features, label = features_and_labels(row_data)
    pprint(features)
    print(label, "\n")
    assert UNWANTED_COLS[0] not in features.keys()
    assert UNWANTED_COLS[1] not in features.keys()
    assert label.shape == [1]

OrderedDict([('pickup_longitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-73.997475], dtype=float32)>),
             ('pickup_latitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([40.68362], dtype=float32)>),
             ('dropoff_longitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-73.99831], dtype=float32)>),
             ('dropoff_latitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([40.71357], dtype=float32)>),
             ('passenger_count',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)])
tf.Tensor([17.7], shape=(1,), dtype=float32) 

OrderedDict([('pickup_longitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-73.97894], dtype=float32)>),
             ('pickup_latitude',
              <tf.Tensor: shape=(1,), dtype=float32, numpy=array([40.76277], dtype=float32)>),
             ('dropoff_longitude',
              <tf.

### Batching

Let's now refactor our `create_dataset` function so that it takes an additional argument `batch_size` and batch the data correspondingly. We will also use the `features_and_labels` function we implemented in order for our dataset to produce tuples of features and labels.

**Lab Task #4b:** Complete the code in the `create_dataset(...)` function below to return a `tf.data` dataset made from the `make_csv_dataset`. Now, the `pattern` and `batch_size` will be given as an arguments of the function but you should set the `column_names` and `column_defaults` as before. You will also apply a `.map(...)` method to create features and labels from each example. 

In [ ]:
def create_dataset(pattern, batch_size):
    dataset = tf.data.experimental.make_csv_dataset(
        pattern, batch_size, CSV_COLUMNS, DEFAULTS
    )
    dataset = # TODO: Your code here.

    return dataset

Let's test that our batches are of the right size:

In [ ]:
BATCH_SIZE = 2

tempds = create_dataset("../data/taxi-train*", batch_size=2)

for X_batch, Y_batch in tempds.take(2):
    pprint({k: v.numpy() for k, v in X_batch.items()})
    print(Y_batch.numpy(), "\n")
    assert len(Y_batch) == BATCH_SIZE

### Shuffling

When training a deep learning model in batches over multiple workers, it is helpful if we shuffle the data. That way, different workers will be working on different parts of the input file at the same time, and so averaging gradients across workers will help. Also, during training, we will need to read the data indefinitely.

Let's refactor our `create_dataset` function so that we can control its behaviour and shuffle data only when the dataset is used for training.

By default, the `make_csv_dataset` function applies shuffling, so please don't forget to specify `shuffle=Flase` to disable default shuffling.

Instead, we will introduce a additional argument `mode` to our function to allow the function body to distinguish the case when it needs to shuffle the data (`mode == "train"`) from when it shouldn't (`mode == "eval"`).

Also, before returning we will want to prefetch 1 data point ahead of time (`dataset.prefetch(1)`) to speedup training:

**Lab Task #4c:** The last step of our `tf.data` dataset will specify shuffling and repeating of our dataset pipeline. Complete the code below to add these three steps to the Dataset pipeline
1. follow the `.map(...)` operation which extracts features and labels with a call to `.cache()` the result.
2. during training, use `.shuffle(...)` and `.repeat()` to shuffle batches and repeat the dataset
3. use `.prefetch(...)` to take advantage of multi-threading and speedup training.

In [ ]:
def create_dataset(pattern, batch_size=1, mode="eval"):
    dataset = tf.data.experimental.make_csv_dataset(
        pattern, batch_size, CSV_COLUMNS, DEFAULTS, shuffle=False
    )

    dataset = # TODO: Your code here.

    if mode == 'train':
        dataset = # TODO: Your code here.

    # take advantage of multi-threading; 1=AUTOTUNE
    dataset = # TODO: Your code here.

    return dataset

Let's check that our function work well in both modes:

In [ ]:
tempds = create_dataset("../data/taxi-train*", 2, "train")
print(list(tempds.take(1)))

In [ ]:
tempds = create_dataset("../data/taxi-valid*", 2, "eval")
print(list(tempds.take(1)))

### Use low-level tf.data API to read the CSV files

`make_csv_dataset` is a handy high-level function that offers a lot of functionalities, but sometimes it doesn't fit some use cases.

To get a more flexible pipeline, we can utilize low-level tf.data APIs to fully control the behavior of the pipeline.

For text-based data including CSV, we can use [`TextLineDataset`](https://www.tensorflow.org/api_docs/python/tf/data/TextLineDataset?version=nightly) for low-level API.

Let's try to create a function to output features in a single Tensor, which is suitable for Sequential API that we will learn in the next section, instead of an ordered dictionary.

**Lab Task #5:** Complete the code in `parse_csv` function and `create_dataset` function below to return single Tensors.
1. use [`tf.strings.split()`](https://www.tensorflow.org/api_docs/python/tf/strings/split) to split each column.  In this case, separater is `,`. 
2. in `create_dataset` function call `parse_csv` function in `.map()` and apply `batch()` with the `batch_size` argument to create batched results.

In [ ]:
def parse_csv(row):
    ds = None  # TODO: Your code here.
    label = tf.strings.to_number(ds[0])
    features = tf.strings.to_number(ds[2:6])  # use some features only
    return features, label


def create_dataset(pattern, batch_size):
    ds = tf.data.TextLineDataset(pattern)
    ds = ds.map()  # TODO: Your code here.
    return ds

In [ ]:
tempds = create_dataset("../data/taxi-train.csv", 2)
print(list(tempds.take(1)))

In the next notebook, we will build the model using this input pipeline.

Copyright 2021 Google Inc.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.